version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ""   # CodeDeploy will replace this with the new task definition during deployment
        LoadBalancerInfo:
          ContainerName: "frontend"
          ContainerPort: 3000